/* Compasso — indice delle aree e degli argomenti.
   Un argomento nuovo: una voce qui + il file argomenti/<id>.js (vedi SCHEMA.md). */
window.COMPASSO_INDICE = {
  aree: [
    { id: 'algebra', nome: 'Algebra', simbolo: 'x', descrizione: 'Numeri, polinomi, equazioni e disequazioni: gli attrezzi di base.', colore: 'a1' },
    { id: 'geometria', nome: 'Geometria', simbolo: '△', descrizione: 'Dalle figure del piano alle curve descritte con le coordinate.', colore: 'a2' },
    { id: 'funzioni', nome: 'Funzioni', simbolo: 'ƒ', descrizione: 'Funzioni, esponenziali, logaritmi e successioni.', colore: 'a3' },
    { id: 'goniometria', nome: 'Goniometria', simbolo: '∠', descrizione: 'Angoli, seno e coseno, formule ed equazioni, triangoli.', colore: 'a4' },
    { id: 'analisi', nome: 'Analisi', simbolo: '∫', descrizione: 'Limiti, derivate, studio di funzione e integrali.', colore: 'a5' },
    { id: 'dati', nome: 'Dati e probabilità', simbolo: '%', descrizione: 'Statistica, calcolo combinatorio e probabilità.', colore: 'a6' }
  ],
  /* Laboratori: esperienze manipolative (file in laboratori/<id>.js, contratto in SCHEMA-LAB.md).
     intro = quello che dice Zenone la prima volta che si apre. */
  laboratori: [
    { id: 'bilancia', argomento: 'equazioni-primo-grado', titolo: 'La bilancia', icona: '⚖️', sotto: 'Casse con la x, pesi e palloncini: risolvi l\'equazione tenendo i piatti in equilibrio.', intro: 'Qualunque cosa fai a un piatto, falla anche all\'altro: è l\'unica regola. Vinci quando su un piatto resta una cassa sola.' },
    { id: 'marea', argomento: 'disequazioni-secondo-grado', titolo: 'Marea', icona: '🌊', sotto: 'Piega la barra, alza il mare fino a quota zero e scegli chi ci vive: alpinista o subacqueo.', intro: 'Le rive segnano le soluzioni dell\'equazione: portale lì e fermati. Sopra il mare è positivo, sotto è negativo.' },
    { id: 'tiro-a-segno', argomento: 'piano-cartesiano-retta', titolo: 'Tiro a segno', icona: '🎯', sotto: 'Punta la retta con due maniglie e falla passare esattamente sopra i palloncini.', intro: 'Sposta P e Q sui punti interi: la retta per due punti è una sola. Quando è al posto giusto, spara.' },
    { id: 'mongolfiera', argomento: 'insiemi-numerici', titolo: 'La mongolfiera', icona: '🎈', sotto: 'Palloncini che tirano su, zavorre che tirano giù: la quota è la somma dei numeri relativi.', intro: 'Attacca palloncini e zavorre: dove si ferma la mongolfiera è la somma. Un +1 e un −1 insieme non la spostano di un dito.' }
  ],
  argomenti: [
    /* ---- Algebra ---- */
    { id: 'insiemi-numerici', area: 'algebra', livello: 1, titolo: 'Insiemi numerici e potenze', breve: 'Naturali, interi, razionali, reali; proprietà delle potenze e notazione scientifica.', prerequisiti: [], parole: ['N', 'Z', 'Q', 'R', 'frazioni', 'potenze', 'esponente', 'notazione scientifica', 'irrazionali', 'valore assoluto'] },
    { id: 'monomi-polinomi', area: 'algebra', livello: 1, titolo: 'Monomi, polinomi e prodotti notevoli', breve: 'Operazioni con monomi e polinomi, quadrato e cubo di binomio, divisione con Ruffini.', prerequisiti: ['insiemi-numerici'], parole: ['monomio', 'polinomio', 'grado', 'prodotti notevoli', 'quadrato di binomio', 'Ruffini', 'divisione', 'resto'] },
    { id: 'scomposizione', area: 'algebra', livello: 1, titolo: 'Scomposizione in fattori', breve: 'Raccoglimento, prodotti notevoli al contrario, trinomio speciale, Ruffini, somma e differenza di cubi.', prerequisiti: ['monomi-polinomi'], parole: ['scomposizione', 'fattorizzazione', 'raccoglimento', 'trinomio', 'differenza di quadrati', 'cubi', 'Ruffini', 'MCD', 'mcm'] },
    { id: 'equazioni-primo-grado', area: 'algebra', livello: 1, titolo: 'Equazioni di primo grado', breve: 'Principi di equivalenza, equazioni intere e fratte, problemi con le equazioni.', prerequisiti: ['monomi-polinomi'], parole: ['equazione', 'primo grado', 'lineare', 'principi di equivalenza', 'fratte', 'condizioni di esistenza', 'impossibile', 'indeterminata'] },
    { id: 'disequazioni-primo-grado', area: 'algebra', livello: 1, titolo: 'Disequazioni di primo grado', breve: 'Disequazioni lineari, intervalli, sistemi di disequazioni, disequazioni fratte con la tabella dei segni.', prerequisiti: ['equazioni-primo-grado'], parole: ['disequazione', 'intervallo', 'sistema di disequazioni', 'tabella dei segni', 'verso', 'fratte'] },
    { id: 'sistemi-lineari', area: 'algebra', livello: 1, titolo: 'Sistemi lineari', breve: 'Sostituzione, riduzione, confronto, Cramer; sistemi determinati, impossibili, indeterminati.', prerequisiti: ['equazioni-primo-grado'], parole: ['sistema', 'sostituzione', 'riduzione', 'Cramer', 'determinante', 'rette', 'determinato', 'impossibile'] },
    { id: 'radicali', area: 'algebra', livello: 1, titolo: 'Radicali', breve: 'Radici n-esime, proprietà, portare dentro e fuori, razionalizzazione, potenze con esponente frazionario.', prerequisiti: ['insiemi-numerici'], parole: ['radicale', 'radice', 'razionalizzazione', 'esponente frazionario', 'indice', 'radicando', 'radicali doppi'] },
    { id: 'equazioni-secondo-grado', area: 'algebra', livello: 1, titolo: 'Equazioni di secondo grado', breve: 'Formula risolutiva, discriminante, formula ridotta, relazioni fra radici e coefficienti, scomposizione del trinomio.', prerequisiti: ['equazioni-primo-grado', 'scomposizione', 'radicali'], parole: ['equazione', 'secondo grado', 'discriminante', 'delta', 'formula risolutiva', 'radici', 'somma e prodotto', 'pure', 'spurie', 'parabola'] },
    { id: 'disequazioni-secondo-grado', area: 'algebra', livello: 1, titolo: 'Disequazioni di secondo grado', breve: 'Studio del segno del trinomio con la parabola, disequazioni fratte e sistemi, di grado superiore.', prerequisiti: ['equazioni-secondo-grado', 'disequazioni-primo-grado'], parole: ['disequazione', 'secondo grado', 'segno del trinomio', 'parabola', 'intervalli', 'fratte', 'tabella dei segni'] },
    { id: 'valore-assoluto-irrazionali', area: 'algebra', livello: 2, titolo: 'Valore assoluto e irrazionali', breve: 'Equazioni e disequazioni con il modulo e con le radici: casi, condizioni, sistemi.', prerequisiti: ['disequazioni-secondo-grado'], parole: ['valore assoluto', 'modulo', 'irrazionale', 'radice', 'condizioni', 'elevare al quadrato', 'sistema'] },
    { id: 'numeri-complessi', area: 'algebra', livello: 2, titolo: 'Numeri complessi', breve: 'Unità immaginaria, forma algebrica e trigonometrica, operazioni, radici n-esime, piano di Gauss.', prerequisiti: ['equazioni-secondo-grado', 'funzioni-goniometriche'], parole: ['complessi', 'immaginario', 'i', 'modulo', 'argomento', 'coniugato', 'forma trigonometrica', 'De Moivre', 'piano di Gauss'] },

    /* ---- Geometria ---- */
    { id: 'geometria-euclidea', area: 'geometria', livello: 1, titolo: 'Geometria euclidea', breve: 'Triangoli e criteri di congruenza, Pitagora ed Euclide, similitudine, aree e circonferenza.', prerequisiti: [], parole: ['triangolo', 'congruenza', 'Pitagora', 'Euclide', 'similitudine', 'Talete', 'area', 'perimetro', 'circonferenza', 'angoli', 'poligoni'] },
    { id: 'piano-cartesiano-retta', area: 'geometria', livello: 1, titolo: 'Piano cartesiano e retta', breve: 'Distanza, punto medio, equazione della retta, coefficiente angolare, parallele e perpendicolari, fasci.', prerequisiti: ['equazioni-primo-grado', 'sistemi-lineari'], parole: ['piano cartesiano', 'retta', 'coefficiente angolare', 'pendenza', 'distanza', 'punto medio', 'parallele', 'perpendicolari', 'fascio', 'distanza punto retta'] },
    { id: 'parabola', area: 'geometria', livello: 2, titolo: 'La parabola', breve: 'Definizione come luogo, equazione, vertice, fuoco, direttrice, rette tangenti, problemi.', prerequisiti: ['piano-cartesiano-retta', 'equazioni-secondo-grado'], parole: ['parabola', 'vertice', 'fuoco', 'direttrice', 'asse', 'tangente', 'luogo geometrico', 'concavità'] },
    { id: 'circonferenza', area: 'geometria', livello: 2, titolo: 'La circonferenza', breve: 'Equazione, centro e raggio, condizioni, posizione retta-circonferenza, tangenti, fasci.', prerequisiti: ['piano-cartesiano-retta', 'equazioni-secondo-grado'], parole: ['circonferenza', 'centro', 'raggio', 'tangente', 'secante', 'esterna', 'fascio', 'asse radicale'] },
    { id: 'ellisse-iperbole', area: 'geometria', livello: 2, titolo: 'Ellisse e iperbole', breve: 'Definizioni come luoghi, equazioni canoniche, fuochi, eccentricità, asintoti, iperbole equilatera e funzione omografica.', prerequisiti: ['circonferenza'], parole: ['ellisse', 'iperbole', 'fuochi', 'eccentricità', 'asintoti', 'semiassi', 'equilatera', 'omografica', 'coniche'] },

    /* ---- Funzioni ---- */
    { id: 'funzioni-generalita', area: 'funzioni', livello: 2, titolo: 'Le funzioni', breve: 'Definizione, dominio e codominio, grafico, iniettive e suriettive, pari e dispari, composte e inverse, trasformazioni del grafico.', prerequisiti: ['piano-cartesiano-retta', 'disequazioni-secondo-grado'], parole: ['funzione', 'dominio', 'codominio', 'immagine', 'iniettiva', 'suriettiva', 'biunivoca', 'pari', 'dispari', 'inversa', 'composta', 'crescente', 'traslazione', 'simmetria'] },
    { id: 'esponenziali', area: 'funzioni', livello: 2, titolo: 'Esponenziali', breve: 'Potenze con esponente reale, la funzione esponenziale e il suo grafico, equazioni e disequazioni esponenziali.', prerequisiti: ['funzioni-generalita', 'radicali'], parole: ['esponenziale', 'base', 'crescita', 'decadimento', 'e', 'Nepero', 'equazioni esponenziali', 'disequazioni esponenziali'] },
    { id: 'logaritmi', area: 'funzioni', livello: 2, titolo: 'Logaritmi', breve: 'Definizione, proprietà, cambiamento di base, funzione logaritmica, equazioni e disequazioni logaritmiche.', prerequisiti: ['esponenziali'], parole: ['logaritmo', 'base', 'proprietà dei logaritmi', 'cambiamento di base', 'logaritmo naturale', 'equazioni logaritmiche', 'condizioni di esistenza'] },
    { id: 'successioni', area: 'funzioni', livello: 2, titolo: 'Successioni e progressioni', breve: 'Successioni, definizione per ricorrenza, progressioni aritmetiche e geometriche, somme, principio di induzione.', prerequisiti: ['esponenziali'], parole: ['successione', 'progressione aritmetica', 'progressione geometrica', 'ragione', 'ricorrenza', 'Fibonacci', 'induzione', 'somma'] },

    /* ---- Goniometria ---- */
    { id: 'funzioni-goniometriche', area: 'goniometria', livello: 2, titolo: 'Funzioni goniometriche', breve: 'Gradi e radianti, circonferenza goniometrica, seno, coseno, tangente, angoli notevoli, relazioni fondamentali, angoli associati, grafici.', prerequisiti: ['funzioni-generalita', 'geometria-euclidea'], parole: ['seno', 'coseno', 'tangente', 'radianti', 'circonferenza goniometrica', 'angoli notevoli', 'angoli associati', 'periodo', 'sinusoide', 'cotangente'] },
    { id: 'formule-goniometriche', area: 'goniometria', livello: 2, titolo: 'Formule goniometriche', breve: 'Addizione e sottrazione, duplicazione, bisezione, parametriche, prostaferesi e Werner.', prerequisiti: ['funzioni-goniometriche'], parole: ['formule di addizione', 'duplicazione', 'bisezione', 'parametriche', 'prostaferesi', 'Werner', 'angolo aggiunto'] },
    { id: 'equazioni-goniometriche', area: 'goniometria', livello: 2, titolo: 'Equazioni e disequazioni goniometriche', breve: 'Equazioni elementari, riconducibili, lineari in seno e coseno, omogenee, disequazioni con la circonferenza.', prerequisiti: ['formule-goniometriche'], parole: ['equazioni goniometriche', 'elementari', 'lineari', 'omogenee', 'metodo dell\'angolo aggiunto', 'disequazioni goniometriche', 'periodicità'] },
    { id: 'trigonometria', area: 'goniometria', livello: 2, titolo: 'Trigonometria', breve: 'Triangoli rettangoli, teorema dei seni, teorema del coseno, area, risoluzione dei triangoli, applicazioni.', prerequisiti: ['funzioni-goniometriche', 'geometria-euclidea'], parole: ['trigonometria', 'triangolo rettangolo', 'teorema dei seni', 'teorema del coseno', 'Carnot', 'area', 'risoluzione dei triangoli', 'corda'] },

    /* ---- Analisi ---- */
    { id: 'limiti', area: 'analisi', livello: 3, titolo: 'Limiti', breve: 'Intorni, definizione di limite, teoremi, calcolo, forme indeterminate, limiti notevoli, confronto di infiniti.', prerequisiti: ['funzioni-generalita', 'esponenziali', 'funzioni-goniometriche'], parole: ['limite', 'intorno', 'infinito', 'forme indeterminate', 'limiti notevoli', 'unicità', 'permanenza del segno', 'confronto', 'gerarchia degli infiniti'] },
    { id: 'continuita-asintoti', area: 'analisi', livello: 3, titolo: 'Continuità e asintoti', breve: 'Funzioni continue, punti di discontinuità, teoremi (Weierstrass, zeri, valori intermedi), asintoti verticali, orizzontali e obliqui.', prerequisiti: ['limiti'], parole: ['continuità', 'discontinuità', 'prima specie', 'seconda specie', 'eliminabile', 'Weierstrass', 'zeri', 'asintoto', 'obliquo', 'orizzontale', 'verticale'] },
    { id: 'derivate', area: 'analisi', livello: 3, titolo: 'Derivate', breve: 'Rapporto incrementale, derivata e retta tangente, regole di derivazione, derivate delle funzioni elementari, punti di non derivabilità.', prerequisiti: ['limiti', 'continuita-asintoti'], parole: ['derivata', 'rapporto incrementale', 'tangente', 'regole di derivazione', 'catena', 'cuspide', 'flesso a tangente verticale', 'punto angoloso', 'velocità'] },
    { id: 'studio-di-funzione', area: 'analisi', livello: 3, titolo: 'Studio di funzione', breve: 'Rolle, Lagrange, de l\'Hôpital, crescenza, massimi e minimi, concavità e flessi, lo schema completo dello studio.', prerequisiti: ['derivate'], parole: ['studio di funzione', 'massimi', 'minimi', 'flessi', 'concavità', 'Rolle', 'Lagrange', 'de l\'Hôpital', 'monotonia', 'derivata seconda', 'grafico'] },
    { id: 'integrali', area: 'analisi', livello: 3, titolo: 'Integrali', breve: 'Primitive e integrale indefinito, metodi (sostituzione, per parti), integrale definito, teorema fondamentale, aree e volumi.', prerequisiti: ['derivate'], parole: ['integrale', 'primitiva', 'indefinito', 'definito', 'per parti', 'sostituzione', 'area', 'volume', 'teorema fondamentale', 'Torricelli', 'Barrow'] },

    /* ---- Dati e probabilità ---- */
    { id: 'statistica', area: 'dati', livello: 1, titolo: 'Statistica descrittiva', breve: 'Frequenze, tabelle e grafici, media, mediana e moda, varianza e deviazione standard, cenni di correlazione.', prerequisiti: ['insiemi-numerici'], parole: ['statistica', 'frequenza', 'media', 'mediana', 'moda', 'varianza', 'deviazione standard', 'istogramma', 'percentuali', 'correlazione'] },
    { id: 'calcolo-combinatorio', area: 'dati', livello: 2, titolo: 'Calcolo combinatorio', breve: 'Principio fondamentale, permutazioni, disposizioni, combinazioni, fattoriale e coefficiente binomiale, binomio di Newton.', prerequisiti: ['insiemi-numerici'], parole: ['combinatorio', 'permutazioni', 'disposizioni', 'combinazioni', 'fattoriale', 'binomiale', 'Newton', 'Tartaglia', 'anagrammi'] },
    { id: 'probabilita', area: 'dati', livello: 2, titolo: 'Probabilità', breve: 'Definizione classica, eventi, unione e intersezione, probabilità condizionata e indipendenza, Bayes, distribuzione binomiale.', prerequisiti: ['calcolo-combinatorio', 'statistica'], parole: ['probabilità', 'evento', 'spazio campionario', 'unione', 'intersezione', 'condizionata', 'indipendenti', 'Bayes', 'binomiale', 'Bernoulli'] }
  ]
};
